<a href="https://colab.research.google.com/github/danlig94/data_science/blob/master/deep_learning/Keras01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import tensorflow as tf

In [8]:
from tensorflow.keras.models import Sequential

model = Sequential()

In [9]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

In [10]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.add(Dense(units=2))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 44        
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


In [18]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [19]:
px.line(data_frame=data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [22]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [24]:
px.line(data_frame=data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [26]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [28]:
px.line(data_frame=data, x='data', y='relu', width=500, height=400)

In [30]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [31]:
px.line(data_frame=data, x='data', y='tanh', width=500, height=400)

In [32]:
model = Sequential()
model.add(Dense(units=8, input_shape=(10,), activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.compile(optimizer='rmsprop',
              loss='mse')

In [33]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [36]:
data[:3]

array([[-5.27091529e-01, -1.66890722e-01, -1.33155649e+00,
        -2.48802592e-01, -1.61166980e-01,  8.32308272e-01,
         5.09922846e-01,  2.19528430e+00, -8.69687440e-01,
         1.37359752e+00, -4.59711252e-03,  1.74372801e+00,
         3.25339876e-01,  2.31667279e+00, -1.46291290e+00,
         2.00635217e+00, -2.10856363e-01,  1.52828229e-01,
         5.05063656e-01, -2.40264176e+00, -5.94057098e-01,
        -8.53035576e-01, -6.67413727e-01,  3.69231378e-01,
         8.12582795e-01, -6.97618879e-01,  7.54138674e-01,
         2.71004962e-01, -4.39226200e-01,  1.71631888e+00,
        -1.25163355e+00,  3.93229094e-02,  1.16030181e+00,
         1.13164377e+00,  6.86549685e-01,  5.61073880e-01,
         3.41849297e-01, -3.75331304e-01, -2.79934730e-01,
        -7.11312921e-01, -1.56365507e+00,  2.54982989e+00,
        -3.29700181e-01,  1.11631148e+00,  1.05141535e-01,
        -6.27124710e-01,  5.49562284e-01, -5.69651194e-01,
         2.17293257e+00, -1.45553347e+00, -7.55300376e-0

In [37]:
labels[:3]

array([[0],
       [1],
       [1]])

In [43]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 0s 1ms/step - loss: 0.7615 - accuracy: 0.5057
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6958 - accuracy: 0.5519
Epoch 3/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6731 - accuracy: 0.5827
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6558 - accuracy: 0.6079
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6405 - accuracy: 0.6321
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6259 - accuracy: 0.6524
Epoch 7/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6112 - accuracy: 0.6714
Epoch 8/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5982 - accuracy: 0.6830
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5848 - accuracy: 0.6961
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5707 - accuracy: 0.7096

In [45]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20
157/157 [==============================] - 0s 1ms/step - loss: 0.7434 - accuracy: 0.5082
Epoch 2/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6968 - accuracy: 0.5438
Epoch 3/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6808 - accuracy: 0.5696
Epoch 4/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6689 - accuracy: 0.5829
Epoch 5/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6579 - accuracy: 0.6079
Epoch 6/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6482 - accuracy: 0.6245
Epoch 7/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6377 - accuracy: 0.6430
Epoch 8/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6275 - accuracy: 0.6535
Epoch 9/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6170 - accuracy: 0.6682
Epoch 10/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6063 - accuracy: 0.6788

In [46]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
250/250 [==============================] - 0s 2ms/step - loss: 0.7540 - accuracy: 0.5104 - val_loss: 0.7318 - val_accuracy: 0.4965
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6940 - accuracy: 0.5549 - val_loss: 0.7266 - val_accuracy: 0.4835
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6712 - accuracy: 0.5918 - val_loss: 0.7245 - val_accuracy: 0.4965
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6545 - accuracy: 0.6160 - val_loss: 0.7271 - val_accuracy: 0.4885
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6389 - accuracy: 0.6359 - val_loss: 0.7301 - val_accuracy: 0.4945
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6230 - accuracy: 0.6611 - val_loss: 0.7331 - val_accuracy: 0.5080
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6076 - accuracy: 0.6762 - val_loss: 0.7402 - val_accuracy: 0.5080
Epoch 

In [47]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [48]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [49]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
250/250 [==============================] - 0s 2ms/step - loss: 0.7555 - accuracy: 0.5089 - val_loss: 0.7261 - val_accuracy: 0.4925
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6912 - accuracy: 0.5575 - val_loss: 0.7205 - val_accuracy: 0.4985
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6705 - accuracy: 0.5870 - val_loss: 0.7231 - val_accuracy: 0.4950
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6544 - accuracy: 0.6221 - val_loss: 0.7270 - val_accuracy: 0.5020
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6392 - accuracy: 0.6384 - val_loss: 0.7326 - val_accuracy: 0.4975
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6246 - accuracy: 0.6559 - val_loss: 0.7392 - val_accuracy: 0.4945
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6090 - accuracy: 0.6773 - val_loss: 0.7508 - val_accuracy: 0.4875
Epoch 

In [50]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [51]:
model.predict(test_data)

array([[0.05512574],
       [0.91145957],
       [0.06581426],
       [0.01649433],
       [0.80728436]], dtype=float32)

In [52]:
model.predict_proba(test_data)

Instructions for updating:
Please use `model.predict()` instead.


array([[0.05512574],
       [0.91145957],
       [0.06581426],
       [0.01649433],
       [0.80728436]], dtype=float32)

In [53]:
model.predict_classes(test_data)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[0],
       [1],
       [0],
       [0],
       [1]], dtype=int32)

In [54]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [56]:
from tensorflow.keras.utils import to_categorical

labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [57]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 2.3208 - accuracy: 0.1015 - val_loss: 2.3045 - val_accuracy: 0.0970
Epoch 2/20
250/250 [==============================] - 0s 2ms/step - loss: 2.3040 - accuracy: 0.1051 - val_loss: 2.3046 - val_accuracy: 0.1000
Epoch 3/20
250/250 [==============================] - 0s 2ms/step - loss: 2.3024 - accuracy: 0.1076 - val_loss: 2.3058 - val_accuracy: 0.0980
Epoch 4/20
250/250 [==============================] - 0s 2ms/step - loss: 2.3010 - accuracy: 0.1051 - val_loss: 2.3079 - val_accuracy: 0.0945
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 2.2994 - accuracy: 0.1115 - val_loss: 2.3073 - val_accuracy: 0.0970
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 2.2956 - accuracy: 0.1142 - val_loss: 2.3079 - val_accuracy: 0.0910
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 2.2932 - accuracy: 0.1171 - val_loss: 2.3092 - val_accuracy: 0.1015
Epoch 

In [58]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[0.07405639, 0.10076826, 0.12593007, 0.14609352, 0.08618798,
        0.08321656, 0.10810038, 0.05831638, 0.11554226, 0.10178814],
       [0.17627226, 0.08902545, 0.13693199, 0.0635573 , 0.07250223,
        0.1020081 , 0.0779491 , 0.08255388, 0.10086712, 0.09833258],
       [0.09307832, 0.10185635, 0.09705627, 0.0948882 , 0.12117555,
        0.10308611, 0.10086673, 0.10443165, 0.08858284, 0.09497796],
       [0.11605172, 0.11003404, 0.12811019, 0.07439303, 0.10173971,
        0.0762981 , 0.09717245, 0.06521639, 0.10217806, 0.12880635],
       [0.07697616, 0.06229388, 0.16224213, 0.06147213, 0.13401742,
        0.09506571, 0.09964402, 0.08428265, 0.0883725 , 0.13563347],
       [0.08838246, 0.07580031, 0.12572053, 0.08890787, 0.11447688,
        0.10104875, 0.10278895, 0.08682719, 0.10485034, 0.11119671],
       [0.09132665, 0.08621858, 0.08522385, 0.13605368, 0.09988162,
        0.0937198 , 0.0716346 , 0.11701064, 0.14629288, 0.07263768],
       [0.09773819, 0.09612537, 0.0924071

In [59]:
model.predict_classes(test_data)

array([3, 0, 4, 9, 2, 2, 8, 9, 5, 9])

In [60]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [61]:
labels[:10]

array([36.02104326, 12.52800323, 26.75520607,  1.2408404 , 21.32178527,
       27.71100286, 48.6300542 ,  9.07482356, 26.05479727, 49.67985737])

In [62]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 0s 2ms/step - loss: 258.2165 - val_loss: 208.0872
Epoch 2/30
250/250 [==============================] - 0s 1ms/step - loss: 208.0655 - val_loss: 208.2013
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 207.8536 - val_loss: 208.3103
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 207.3324 - val_loss: 208.4434
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 206.9544 - val_loss: 208.6083
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 206.7906 - val_loss: 208.6205
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 206.6236 - val_loss: 208.6635
Epoch 8/30
250/250 [==============================] - 0s 1ms/step - loss: 206.2811 - val_loss: 209.4624
Epoch 9/30
250/250 [==============================] - 0s 1ms/step - loss: 206.1152 - val_loss: 209.0419
Epoch 10/30
250/250 [==============================] - 0s 1ms/st

In [63]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 [==============================] - 0s 2ms/step - loss: 13.5345 - mse: 259.1852 - val_loss: 12.4652 - val_mse: 208.4892
Epoch 2/10
250/250 [==============================] - 0s 1ms/step - loss: 12.4707 - mse: 208.7219 - val_loss: 12.4691 - val_mse: 208.6999
Epoch 3/10
250/250 [==============================] - 0s 1ms/step - loss: 12.4478 - mse: 208.4400 - val_loss: 12.4732 - val_mse: 208.3352
Epoch 4/10
250/250 [==============================] - 0s 1ms/step - loss: 12.4378 - mse: 207.9721 - val_loss: 12.4833 - val_mse: 208.8943
Epoch 5/10
250/250 [==============================] - 0s 1ms/step - loss: 12.4162 - mse: 207.8165 - val_loss: 12.5423 - val_mse: 211.4065
Epoch 6/10
250/250 [==============================] - 0s 1ms/step - loss: 12.4094 - mse: 207.5083 - val_loss: 12.4862 - val_mse: 208.9384
Epoch 7/10
250/250 [==============================] - 0s 1ms/step - loss: 12.3947 - mse: 207.1337 - val_loss: 12.4818 - val_mse: 208.8098
Epoch 8/10
250/250 [==============

In [64]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[25.828545],
       [27.268457],
       [24.59082 ],
       [26.498575],
       [23.156942],
       [25.752932],
       [24.756563],
       [29.1664  ],
       [26.04076 ],
       [25.642555]], dtype=float32)