<a href="https://colab.research.google.com/github/danlig94/data_science/blob/master/NumPy/NumPy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.5'

In [2]:
A = np.arange(20)
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
A[0, 0]

0

In [4]:
A[0, :]

array([0, 1, 2, 3, 4])

In [5]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [6]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [7]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


#default rows
#flat for iterations


In [8]:
A = np.arange(30)
A = A.reshape(10, -1)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [9]:
A = A.T
A

array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29]])

In [10]:
A.ravel()

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27,  1,  4,  7, 10, 13, 16, 19,
       22, 25, 28,  2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [11]:
A = np.arange(start=10, stop=-10, step=-1)
print(A.size)
A = A.reshape(5, -1)
A

20


array([[10,  9,  8,  7],
       [ 6,  5,  4,  3],
       [ 2,  1,  0, -1],
       [-2, -3, -4, -5],
       [-6, -7, -8, -9]])

In [12]:
A > 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [13]:
np.bitwise_or(A < -1, A > 2)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [14]:
A[np.bitwise_or(A < -1, A > 2)]

array([10,  9,  8,  7,  6,  5,  4,  3, -2, -3, -4, -5, -6, -7, -8, -9])

In [15]:
A = np.zeros((10,10))
A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
A[4:6, :] = 1
A[:, 4:6] = 1
A

array([[0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.]])

In [17]:
B = np.full((5, 5), fill_value=5)
B

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [18]:
B[1:4, 1:4] = 3
B

array([[5, 5, 5, 5, 5],
       [5, 3, 3, 3, 5],
       [5, 3, 3, 3, 5],
       [5, 3, 3, 3, 5],
       [5, 5, 5, 5, 5]])

In [19]:
B[2, 2] = 1
B

array([[5, 5, 5, 5, 5],
       [5, 3, 3, 3, 5],
       [5, 3, 1, 3, 5],
       [5, 3, 3, 3, 5],
       [5, 5, 5, 5, 5]])