<a href="https://colab.research.google.com/github/danlig94/data_science/blob/master/NumPy/NumPy03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.5'

In [2]:
x = np.array([-2, 5])
x

array([-2,  5])

In [3]:
norm = np.sqrt(x[0]**2 + x[1]**2)
norm


5.385164807134504

In [4]:
np.linalg.norm(x)

5.385164807134504

In [5]:
p = np.array([3, 0])
q = np.array([0, 4])

In [6]:
np.linalg.norm(p-q)

5.0

In [7]:
A = np.array([[1, 5], [-2, 6]])
A

array([[ 1,  5],
       [-2,  6]])

In [8]:
det = (A[0, 0] * A[-1, -1]) - (A[0, -1] * A[-1, 0])
det

16

In [9]:
round(np.linalg.det(A))

16.0

In [10]:
trace = A[0, 0] + A[-1, -1]
trace

7

In [11]:
np.trace(A)

7

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
B = np.linalg.inv(A)
B

array([[ 0.375 , -0.3125],
       [ 0.125 ,  0.0625]])