<a href="https://colab.research.google.com/github/danlig94/data_science/blob/master/NumPy/NumPy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.5'

In [2]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x
print(x)

[0 1 2 3 4 5 6 7 8 9]


#print (x) display only the contents of the array, x itself also shows the type of the object

#the code prints the last line unless you use print first

In [3]:
print(x)
x

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(x)

numpy.ndarray

In [5]:
x.ndim

1

In [6]:
x.shape

(10,)

In [7]:
x.size

10

In [8]:
x.dtype

dtype('int64')

In [9]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
x.shape


(3, 3)

In [11]:
x = np.array(
    [[[1,2,3,4],
      [3,4,5,6]],
     
     [[5,6,7,8],
      [7,8,9,0]],
     
     [[9,0,1,2],
      [1,2,3,4]]]
)
x

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[5, 6, 7, 8],
        [7, 8, 9, 0]],

       [[9, 0, 1, 2],
        [1, 2, 3, 4]]])

In [12]:
x.shape

(3, 2, 4)

In [13]:
x.ndim

3

In [14]:
x = np.array([1,2,3,4,5], dtype="float")
print(x.dtype)
x

float64


array([1., 2., 3., 4., 5.])

In [15]:
x = np.array([1,2,3,4,5], dtype='int')
print(x.dtype)
x

int64


array([1, 2, 3, 4, 5])

In [16]:
zeros = np.zeros(shape=(4,5))
print(zeros.dtype)
zeros

float64


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
ones = np.ones(shape=(7,6), dtype="int")
ones

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [18]:
fives = np.full(shape=(3,4), fill_value=5, dtype="int")
fives

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x = np.arange(start=0, stop=5)
print(x.dtype)
x

int64


array([0, 1, 2, 3, 4])

In [21]:
x = np.arange(start=0, stop=5, step=0.5)
print(x.dtype)
x

float64


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [22]:
x = np.linspace(start=0, stop=9, num=21)
x

array([0.  , 0.45, 0.9 , 1.35, 1.8 , 2.25, 2.7 , 3.15, 3.6 , 4.05, 4.5 ,
       4.95, 5.4 , 5.85, 6.3 , 6.75, 7.2 , 7.65, 8.1 , 8.55, 9.  ])

In [23]:
x = np.arange(start=0, stop=1, step=0.1)
print(x.size)
x

10


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [24]:
x = x.reshape((5, -1))
print(x.shape)
x

(5, 2)


array([[0. , 0.1],
       [0.2, 0.3],
       [0.4, 0.5],
       [0.6, 0.7],
       [0.8, 0.9]])

In [25]:
x = x.reshape((-1, 2))
print(x.shape)
x

(5, 2)


array([[0. , 0.1],
       [0.2, 0.3],
       [0.4, 0.5],
       [0.6, 0.7],
       [0.8, 0.9]])

In [26]:
A = np.linspace(start=1, stop=15, num=15)
print(A.size)
A

15


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [27]:
A = A.reshape((5,-1))
A

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [28]:
B = np.arange(start=5, stop=20)
print(B.size)
B = B.reshape((5, -1))
B

15


array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [29]:
A.size == B.size

True

In [30]:
A + B

array([[ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.],
       [24., 26., 28.],
       [30., 32., 34.]])

In [31]:
np.add(A, B)

array([[ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.],
       [24., 26., 28.],
       [30., 32., 34.]])

In [32]:
A - B

array([[-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.]])

In [33]:
np.subtract(A, B)

array([[-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.]])

In [34]:
A * B

array([[  5.,  12.,  21.],
       [ 32.,  45.,  60.],
       [ 77.,  96., 117.],
       [140., 165., 192.],
       [221., 252., 285.]])

In [35]:
np.multiply(A, B)

array([[  5.,  12.,  21.],
       [ 32.,  45.,  60.],
       [ 77.,  96., 117.],
       [140., 165., 192.],
       [221., 252., 285.]])

In [36]:
A / B

array([[0.2       , 0.33333333, 0.42857143],
       [0.5       , 0.55555556, 0.6       ],
       [0.63636364, 0.66666667, 0.69230769],
       [0.71428571, 0.73333333, 0.75      ],
       [0.76470588, 0.77777778, 0.78947368]])

In [37]:
np.divide(A, B)

array([[0.2       , 0.33333333, 0.42857143],
       [0.5       , 0.55555556, 0.6       ],
       [0.63636364, 0.66666667, 0.69230769],
       [0.71428571, 0.73333333, 0.75      ],
       [0.76470588, 0.77777778, 0.78947368]])

In [38]:
A + 3*B

array([[16., 20., 24.],
       [28., 32., 36.],
       [40., 44., 48.],
       [52., 56., 60.],
       [64., 68., 72.]])

In [39]:
np.add(A, (3*B))

array([[16., 20., 24.],
       [28., 32., 36.],
       [40., 44., 48.],
       [52., 56., 60.],
       [64., 68., 72.]])

In [40]:
X = np.arange(start=10, stop=22)
print(X.size)
X = X.reshape((4, -1))
print(X.shape)
X

12
(4, 3)


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [41]:
Y = np.arange(start=22, stop=34)
print(Y.size)
Y = Y.reshape((3,-1))
print(Y.shape)
Y

12
(3, 4)


array([[22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [42]:
X @ Y

array([[ 866,  899,  932,  965],
       [1100, 1142, 1184, 1226],
       [1334, 1385, 1436, 1487],
       [1568, 1628, 1688, 1748]])

In [43]:
np.dot(X, Y)

array([[ 866,  899,  932,  965],
       [1100, 1142, 1184, 1226],
       [1334, 1385, 1436, 1487],
       [1568, 1628, 1688, 1748]])

In [44]:
X.dot(Y)

array([[ 866,  899,  932,  965],
       [1100, 1142, 1184, 1226],
       [1334, 1385, 1436, 1487],
       [1568, 1628, 1688, 1748]])

In [45]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [46]:
np.random.randn(5)

array([ 0.74159174,  1.55291372, -2.2683282 ,  1.33354538, -0.84272405])

#random.randn standard normal

In [47]:
np.random.randn(4,5)

array([[ 1.96992445,  1.26611853, -0.50587654,  2.54520078,  1.08081191],
       [ 0.48431215,  0.57914048, -0.18158257,  1.41020463, -0.37447169],
       [ 0.27519832, -0.96075461,  0.37692697,  0.03343893,  0.68056724],
       [-1.56349669, -0.56669762, -0.24214951,  1.51439128, -0.3330574 ]])

#random.rand compartment (0-1>

In [48]:
np.random.rand(3,4)

array([[0.6176355 , 0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195, 0.6976312 ],
       [0.06022547, 0.66676672, 0.67063787, 0.21038256]])

In [49]:
x = np.random.randint(low=10, high=15, size=10)
x

array([13, 10, 13, 14, 11, 12, 14, 13, 14, 14])

In [50]:
np.random.choice(x)

11

In [51]:
np.random.shuffle(x)
x

array([14, 12, 10, 13, 14, 13, 13, 14, 11, 14])

In [52]:
np.exp(1)

2.718281828459045

In [53]:
np.sqrt(16)

4.0

In [54]:
np.all(x)

True

In [55]:
np.any(x)

True

In [56]:
np.any([0,0,0,1])

True

In [57]:
np.sqrt(x)

array([3.74165739, 3.46410162, 3.16227766, 3.60555128, 3.74165739,
       3.60555128, 3.60555128, 3.74165739, 3.31662479, 3.74165739])

In [58]:
x = np.random.rand(15)
x

array([0.65632959, 0.13818295, 0.19658236, 0.36872517, 0.82099323,
       0.09710128, 0.83794491, 0.09609841, 0.97645947, 0.4686512 ,
       0.97676109, 0.60484552, 0.73926358, 0.03918779, 0.28280696])

In [59]:
np.argmax(x)

10

In [60]:
x[np.argmax(x)]

0.9767610881903371

In [61]:
np.argsort(x)

array([13,  7,  5,  1,  2, 14,  3,  9, 11,  0, 12,  4,  6,  8, 10])

In [62]:
np.min(x)

0.039187792254320675

In [63]:
np.max(x)

0.9767610881903371

In [64]:
np.mean(x)

0.4866622335342788

In [65]:
np.median(x)

0.4686512016477016

In [66]:
np.std(x)

0.3253452081704004